# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    deploy:
      docker:
        - image: circleci/openjdk:8u222-jdk-stretch
      steps:
        - checkout
        - run :
            name: build jar
            command: mvn clean install && java -jar target/codenation-0.0.1-SNAPSHOT.jar
        - run:
            name: Deploy Master to Heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

    workflows:
      version: 2
      workflow:
        jobs:
          - build
          - deploy:
              requires:
                - build
              filters:
                branches:
                  only: master